#!/usr/bin/env node
"use strict";

// Generates config.js (the PUBLIC browser config for the shared-save backend
// - see config.example.js) from SUPABASE_URL / SUPABASE_ANON_KEY, read from
// the environment or .env.local. Lets localhost use the same backend the
// Netlify build injects, without committing the keys (config.js is gitignored;
// both values are public-safe). Netlify uses scripts/build-netlify-site.js
// instead, which reads the same env vars.
//
//   node scripts/write-config.js
//
// .env.local currently ships the anon key but not SUPABASE_URL (the project
// URL lives in the ignored release doc) - add a line
//   SUPABASE_URL=https://<your-ref>.supabase.co
// to .env.local, or set it in the environment, before running this.

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");

function loadEnv() {
  const env = { ...process.env };
  const envFile = path.join(root, ".env.local");
  if (fs.existsSync(envFile)) {
    for (const line of fs.readFileSync(envFile, "utf8").split(/\r?\n/)) {
      const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/.exec(line);
      if (m && env[m[1]] === undefined) env[m[1]] = m[2].replace(/^["']|["']$/g, "");
    }
  }
  return env;
}

const env = loadEnv();
const url = env.SUPABASE_URL;
const key = env.SUPABASE_ANON_KEY;

if (!url || !key || /YOUR_PROJECT_REF|YOUR_PUBLIC/.test(url + key)) {
  console.error(
    "Missing SUPABASE_URL and/or SUPABASE_ANON_KEY (checked environment + .env.local).\n" +
      "Add them (SUPABASE_URL=https://<ref>.supabase.co) and re-run. config.js NOT written."
  );
  process.exit(1);
}

const out =
  "// Generated by scripts/write-config.js - gitignored, do not edit by hand.\n" +
  "window.EU5_CONFIG = {\n" +
  `  supabaseUrl: ${JSON.stringify(url)},\n` +
  `  supabaseAnonKey: ${JSON.stringify(key)},\n` +
  "};\n";

fs.writeFileSync(path.join(root, "config.js"), out);
console.log("Wrote config.js");
